''' storing final columns for RandomForestRegressor - all of these positively support better target predictions '''

final_cols = [
            'apparelmensbigtall_False',
            'businessowner_Builder',
            'hhpresence',
            'percimprovedlot',
            'apparelmensbigtall_True',
            'valuehunter_False',
            'homeimprovementdiy_False',
            'buyerchildrensbabycare_False',
            'valuehunter_True',
            'recenthomebuyer_NO',
            'grandchildren_True',
            'educationonline_False',
            'homevaluerange_$175,000 to $199,999',
            'homeimprovementdiy_True',
            'homevaluerange_$250,000 to $274,999',
            'militarymemorabiliaweapons_True',
            'unsecuredcreditcapacity',
            'discincome',
            'discretionaryincomerange_$125,000 to $149,999',
            'photography_False',
            'homevaluerange_$275,000 to $299,999',
            'millionaire_NO',
            'collectoravid_True',
            'smokingtobacco_False',
            'donorcapacityrange_Over $5,000',
            'soho_NO',
            'buyerchildrensbabycare_True',
            'collectiblesstamps_True',
            'networth',
            'grandchildren_False',
            'estcreditrating_550 - 599',
            'smokingtobacco_True',
            'recenthomebuyer_RECENT BUYER',
            'homevaluerange_$25,000 to $49,999',
            'collectiblesstamps_False',
            'totalmarketvalue',
            'cctravelentertainment_False',
            'homevaluerange_$2,500,000 to $4,999,999',
            'homevaluerange_$75,000 to $99,999',
            'ccamericanexpress_True',
            'career_False',
            'singleparent_False',
            'donorcapacity',
            'marketlandvalue',
            'estcreditrating_600 - 649',
            'estcreditrating_0 - 499',
            'readingaudiobooks_True',
            'apparelinfanttoddlers_False',
            'totalpermits',
            'homeassessedvalue_Less than $50,000',
            'militarymemorabiliaweapons_False',
            'collegegraduate_True',
            'singleparent_True',
            'apparelchildrens_False',
            'collectiblescoins_True',
            'christianfamilies_True',
            'newteendrivergender_M',
            'sciencespace_True',
            'lengthofresidencedescription_Over 15 Years',
            'readingreligiousinspirational_False',
            'discretionaryincomerange_Up to $9,999',
            'musiclistener_True',
            'donorcapacityrange_Up to $499',
            'mailorderresponder_NO',
            'sportsgolf_True',
            'autopartsaccessories_False',
            'collectiblesgeneral_False',
            'percprodbuilder',
            'sportsgolf_False',
            'gamingcasino_True',
            'homeassessedvalue_$100,000 - $149,999',
            'homeassessedvalue_ $250,000 - $299,999',
            'homevaluerange_$1,500,000 to $2,499,999',
            'sewingknittingneedlework_False',
            'percsublot',
            'ccbank_True',
            'readingreligiousinspirational_True',
            'homevaluerange_$5,000,000 to $9,999,999',
            'maritalstatus_MARRIED',
            'buyerchildrenslearningtoys_False',
            'spectatorsportstvsports_True',
            'homevaluerange_$225,000 to $249,999',
            'popgrowth2010',
            'lengthofresidencedescription_6 to 9 Years',
            'spectatorsportssoccer_True',
            'collectiblescoins_False',
            'youngadultinhousehold_False',
            'sportsleisure_True',
            'photography_True',
            'spectatorsportssoccer_False',
            'pop5yrproj',
            'donorveterans_False',
            'medianhomevaluerange_$150,000 to $174,999',
            'medianhomevaluerange_$275,000 to $299,999',
            'buyermerchandisefemale_False',
            'ccvisa_False',
            'autopartsaccessories_True',
            'discretionaryincomerange_$70,000 to $99,999',
            'discretionaryincomerange_$50,000 to $69,999',
            'christianfamilies_False',
            'photographyvideoequipment_True',
            'homevaluerange_$150,000 to $174,999',
            'homeassessedvalue_ $150,000 - $199,999',
            'maritalstatus_SINGLE',
            'estcreditrating_500 - 549',
            'sciencespace_False',
            'gamescomputergames_False',
            'unsecuredcreditcapacityrange_Up to $4,999',
            'generationsinhousehold_ADULT/CHILD/PARENT',
            'buyeronline_False',
            'medianhomevaluerange_$300,000 to $349,999',
            'workingwoman_NO',
            'cookinggeneral_True',
            'sportsequestrian_False',
            'culturalartisticliving_False',
            'ccunknown_True',
            'donorpoliticalconservative_False',
            'historymilitary_False',
            'buyeronline_True',
            'sportsequestrian_True',
            'medfamincome',
            'diyliving_False',
            'spectatorsportsgeneral_False',
            'homeassessedvalue_$500,000 - $599,999',
            'homevaluerange_$350,000 to $399,999',
            'ccupscaledept_False',
            'musicplayer_True',
            'buyermembershipclub_True',
            'ccdiscover_True',
            'spectatorsportshockey_True',
            'estcreditrating_700 - 749',
            'spectatorsportsracing_False',
            'buyerchildrensbacktoschool_True',
            'sewingknittingneedlework_True',
            'ccvisa_True',
            'householdsize',
            'buyercraftshobbies_True',
            'tvsatellitedish_YES',
            'woodworking_True',
            'outdoorenthusiastgeneral_False',
            'moviegrouping_True',
            'youngadultinhousehold_True',
            'travelcruises_True',
            'culturalartisticliving_True',
            'workingwoman_YES',
            'mailorderdonor_YES',
            'ccgasdeptretail_False',
            'homeassessedvalue_$700,000 - $799,999',
            'homefurnishingsdecorating_True',
            'networthrange_Over $1,500,000',
            'homevaluerange_$100,000 to $124,999',
            'apparelmensyoung_False',
            'homevaluerange_$50,000 to $74,999',
            'rvowner_TRUE',
            'moviecollector_False',
            'homefurnishingsdecorating_False',
            'autowork_True',
            'sportyliving_False',
            'newteendrivergender_F',
            'businessowner_Owner',
            'professionalliving_False',
            'moviegrouping_False',
            'diyliving_True',
            'discretionaryincomerange_$30,000 to $49,999',
            'apparelchildrens_True'

]
